#!/usr/bin/env bash
# Configure and deploy an independent DIGITAfrica Tier-1 or Tier-2 workshop.
#
# Profiles:
#   basic                  Dummy-login workshop deployment.
#   managed-keycloak-oidc  Trusted TLS, managed Keycloak, and JupyterHub OIDC.
#
# The generated inventory and variables are local-only and excluded from Git.

set -Eeuo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/../.." && pwd)"
WORKSHOP_ROOT="${REPO_ROOT}/inventories/workshop"
DEPLOY_SCRIPT="${SCRIPT_DIR}/deploy-infrastructure.sh"
HEALTH_SCRIPT="${SCRIPT_DIR}/health-check.sh"
KEYCLOAK_BOOTSTRAP="${SCRIPT_DIR}/keycloak-bootstrap.sh"

WORKSHOP_DIR=""
INVENTORY=""
VARS_DIR=""
VARS_FILE=""
DEPLOYMENT_TIER=""
PROFILE=""
CENTRAL_HOST=""
PUBLIC_HOST=""
SSH_USER="adam"
ADMIN_USER="admin"
WORKER_HOSTS=()
WORKSHOP_TIMEZONE="${WORKSHOP_TIMEZONE:-Europe/Amsterdam}"
TLS_MODE="selfsigned"
TLS_CERT_DIR=""
TLS_ACME_EMAIL=""
STORAGE_CLASS="local-path"
IDENTITY_ENABLED="false"
KEYCLOAK_REALM="digitafrica"
KEYCLOAK_ADMIN_USER="admin"
KEYCLOAK_NAMESPACE="digitafrica-identity"
KEYCLOAK_ADMIN_PASSWORD_FILE=""
RUN_DEPLOYMENT="false"

info() { printf '[INFO] %s\n' "$*"; }
warn() { printf '[WARNING] %s\n' "$*" >&2; }
die() { printf '[ERROR] %s\n' "$*" >&2; exit 1; }

usage() {
  cat <<'USAGE'
Usage:
  scripts/admin/setup-wizard.sh
  scripts/admin/setup-wizard.sh --deploy

Creates/replaces a local ignored Tier-1 or Tier-2 inventory and configuration.

--deploy
  After configuration confirmation, offer to run the selected deployment
  workflow immediately.
USAGE
}

require_command() {
  command -v "$1" >/dev/null 2>&1 ||
    die "Required command not found: $1"
}

require_executable() {
  [[ -x "$1" ]] || die "Required executable is missing: $1"
}

confirm() {
  local answer
  read -r -p "$1 [y/N]: " answer
  [[ "${answer,,}" == "y" || "${answer,,}" == "yes" ]]
}

prompt_required() {
  local variable_name="$1"
  local prompt="$2"
  local default_value="${3:-}"
  local value

  while true; do
    if [[ -n "$default_value" ]]; then
      read -r -p "${prompt} [${default_value}]: " value
      value="${value:-$default_value}"
    else
      read -r -p "${prompt}: " value
    fi

    [[ -n "$value" ]] || {
      warn "A value is required."
      continue
    }

    printf -v "$variable_name" '%s' "$value"
    return 0
  done
}

prompt_choice() {
  local variable_name="$1"
  local prompt="$2"
  local default_value="$3"
  shift 3

  local value candidate
  local -a allowed=("$@")

  while true; do
    read -r -p "${prompt} [${default_value}]: " value
    value="${value:-$default_value}"

    for candidate in "${allowed[@]}"; do
      if [[ "$value" == "$candidate" ]]; then
        printf -v "$variable_name" '%s' "$value"
        return 0
      fi
    done

    warn "Choose one of: ${allowed[*]}"
  done
}

validate_host() {
  [[ "$1" =~ ^[A-Za-z0-9][A-Za-z0-9._:-]*$ ]]
}

validate_identifier() {
  [[ "$1" =~ ^[A-Za-z_][A-Za-z0-9_.-]*$ ]]
}

yaml_dq() {
  local value="$1"
  value="${value//\\/\\\\}"
  value="${value//\"/\\\"}"
  value="${value//$'\n'/}"
  printf '"%s"' "$value"
}

ensure_local_git_exclude() {
  local exclude_file
  local pattern='inventories/workshop/'

  git -C "${REPO_ROOT}" rev-parse --is-inside-work-tree >/dev/null 2>&1 ||
    return 0

  exclude_file="$(git -C "${REPO_ROOT}" rev-parse --git-path info/exclude)"
  [[ "$exclude_file" = /* ]] ||
    exclude_file="${REPO_ROOT}/${exclude_file}"

  mkdir -p "$(dirname "$exclude_file")"
  touch "$exclude_file"

  if ! grep -Fqx "$pattern" "$exclude_file"; then
    printf '\n# Local configuration generated by setup-wizard.sh\n%s\n' \
      "$pattern" >> "$exclude_file"
  fi
}

check_prerequisites() {
  require_command ansible
  require_command ansible-playbook
  require_command git
  require_command ssh
  require_command stat
  require_executable "${DEPLOY_SCRIPT}"
  require_executable "${HEALTH_SCRIPT}"
  require_executable "${KEYCLOAK_BOOTSTRAP}"
}

choose_deployment_tier() {
  cat <<'MENU'

Choose deployment tier:
  1) Tier-1
  2) Tier-2
MENU

  local choice
  prompt_choice choice "Deployment tier" "1" 1 2

  if [[ "$choice" == "1" ]]; then
    DEPLOYMENT_TIER="tier1"
  else
    DEPLOYMENT_TIER="tier2"
  fi

  WORKSHOP_DIR="${WORKSHOP_ROOT}/${DEPLOYMENT_TIER}"
  INVENTORY="${WORKSHOP_DIR}/hosts.ini"
  VARS_DIR="${WORKSHOP_DIR}/group_vars"
  VARS_FILE="${VARS_DIR}/all.yml"
}

choose_profile() {
  cat <<'MENU'

Choose deployment profile:
  1) Basic workshop
     Self-signed TLS and JupyterHub dummy login.

  2) Managed-Keycloak OIDC
     Trusted TLS, PostgreSQL, Keycloak, and JupyterHub OIDC.
MENU

  local choice
  prompt_choice choice "Deployment profile" "1" 1 2

  if [[ "$choice" == "1" ]]; then
    PROFILE="basic"
    TLS_MODE="selfsigned"
    IDENTITY_ENABLED="false"
    return 0
  fi

  PROFILE="managed-keycloak-oidc"
  IDENTITY_ENABLED="true"

  cat <<'MENU'

Managed-Keycloak OIDC requires trusted HTTPS:
  1) Let's Encrypt
  2) Provided TLS certificate
MENU

  prompt_choice choice "Trusted TLS mode" "1" 1 2
  case "$choice" in
    1)
      TLS_MODE="letsencrypt"
      prompt_required TLS_ACME_EMAIL "ACME registration email"
      ;;
    2)
      TLS_MODE="provided"
      prompt_required TLS_CERT_DIR \
        "Control-machine directory containing tls.crt and tls.key"
      [[ -f "${TLS_CERT_DIR}/tls.crt" ]] ||
        die "Missing ${TLS_CERT_DIR}/tls.crt"
      [[ -f "${TLS_CERT_DIR}/tls.key" ]] ||
        die "Missing ${TLS_CERT_DIR}/tls.key"
      ;;
  esac

  prompt_required STORAGE_CLASS "Kubernetes StorageClass" "local-path"
}

collect_topology() {
  prompt_required CENTRAL_HOST \
    "Central ${DEPLOYMENT_TIER^} server hostname or IP"

  validate_host "$CENTRAL_HOST" ||
    die "Invalid central host: ${CENTRAL_HOST}"

  prompt_required SSH_USER "SSH username" "adam"
  validate_identifier "$SSH_USER" ||
    die "Invalid SSH username: ${SSH_USER}"

  [[ "$SSH_USER" == "adam" ]] ||
    die "The current workshop roles require the Linux account adam."

  prompt_required ADMIN_USER "JupyterHub administrator username" "admin"
  validate_identifier "$ADMIN_USER" ||
    die "Invalid JupyterHub administrator username: ${ADMIN_USER}"

  local workers_line worker
  while true; do
    read -r -p \
      "Worker VM hostnames or IPs (space-separated; at least two): " \
      workers_line
    read -r -a WORKER_HOSTS <<< "$workers_line"

    [[ "${#WORKER_HOSTS[@]}" -ge 2 ]] || {
      warn "At least two worker VMs are required."
      continue
    }

    for worker in "${WORKER_HOSTS[@]}"; do
      validate_host "$worker" || die "Invalid worker host: ${worker}"
      [[ "$worker" != "$CENTRAL_HOST" ]] ||
        die "A worker cannot equal the central host."
    done

    [[ "$(printf '%s\n' "${WORKER_HOSTS[@]}" | sort -u | wc -l)" \
      -eq "${#WORKER_HOSTS[@]}" ]] || {
      warn "Each worker must be listed only once."
      continue
    }

    break
  done

  prompt_required PUBLIC_HOST \
    "Public hostname or IP for JupyterHub and Keycloak" "${CENTRAL_HOST}"

  validate_host "$PUBLIC_HOST" ||
    die "Invalid public host: ${PUBLIC_HOST}"

  if [[ "$IDENTITY_ENABLED" == "true" &&
        "$TLS_MODE" == "letsencrypt" &&
        "$PUBLIC_HOST" =~ ^[0-9.]+$ ]]; then
    die "Let's Encrypt requires a DNS hostname, not an IPv4 address."
  fi

  prompt_required WORKSHOP_TIMEZONE \
    "Timezone for workshop VMs" "${WORKSHOP_TIMEZONE}"
}

check_ssh_access() {
  local host

  for host in "$CENTRAL_HOST" "${WORKER_HOSTS[@]}"; do
    printf 'Checking %s@%s ... ' "$SSH_USER" "$host"
    if ssh -o BatchMode=yes -o ConnectTimeout=10 \
      -o StrictHostKeyChecking=accept-new \
      "${SSH_USER}@${host}" true; then
      printf 'OK\n'
    else
      printf 'FAILED\n'
      die "SSH key authentication failed for ${SSH_USER}@${host}"
    fi
  done
}

prepare_keycloak_admin_password() {
  [[ "$IDENTITY_ENABLED" == "true" ]] || return 0

  KEYCLOAK_ADMIN_PASSWORD_FILE="${REPO_ROOT}/secrets/keycloak/${PUBLIC_HOST}/${KEYCLOAK_REALM}/master-admin.password"

  if [[ -f "$KEYCLOAK_ADMIN_PASSWORD_FILE" ]]; then
    [[ "$(stat -c '%a' "$KEYCLOAK_ADMIN_PASSWORD_FILE")" == "600" ]] ||
      die "Existing Keycloak password file must have mode 0600: ${KEYCLOAK_ADMIN_PASSWORD_FILE}"
    info "Retaining existing protected Keycloak administrator password record."
    return 0
  fi

  local password confirmation
  read -r -s -p \
    "Initial Keycloak master administrator password: " password
  printf '\n'
  read -r -s -p "Repeat Keycloak master administrator password: " confirmation
  printf '\n'

  [[ -n "$password" ]] || die "Keycloak administrator password must not be empty."
  [[ "$password" == "$confirmation" ]] ||
    die "Keycloak administrator passwords do not match."

  umask 077
  mkdir -p "$(dirname "$KEYCLOAK_ADMIN_PASSWORD_FILE")"
  chmod 700 "$(dirname "$KEYCLOAK_ADMIN_PASSWORD_FILE")"
  printf '%s\n' "$password" > "$KEYCLOAK_ADMIN_PASSWORD_FILE"
  chmod 600 "$KEYCLOAK_ADMIN_PASSWORD_FILE"
  unset password confirmation
}

write_inventory() {
  mkdir -p "$VARS_DIR"

  cat > "$INVENTORY" <<EOF_INVENTORY
# Generated by scripts/admin/setup-wizard.sh. Do not commit this local file.
[${DEPLOYMENT_TIER}_server]
${DEPLOYMENT_TIER}-server ansible_host=${CENTRAL_HOST}

[${DEPLOYMENT_TIER}_agents]
EOF_INVENTORY

  local index=1 worker
  for worker in "${WORKER_HOSTS[@]}"; do
    printf '%s-worker-%s ansible_host=%s\n' \
      "$DEPLOYMENT_TIER" "$index" "$worker" >> "$INVENTORY"
    index=$((index + 1))
  done

  cat >> "$INVENTORY" <<EOF_INVENTORY

[all:vars]
ansible_user=${SSH_USER}
ansible_become=true
EOF_INVENTORY
}

write_variables() {
  local scheme="https"

  cat > "$VARS_FILE" <<EOF_VARIABLES
# Generated by scripts/admin/setup-wizard.sh. Do not commit this local file.
# Profile: ${PROFILE}
timezone: $(yaml_dq "${WORKSHOP_TIMEZONE}")

${DEPLOYMENT_TIER}:
  profile: $(yaml_dq "${PROFILE}")
  expose_mode: "ingress"
  tls_mode: $(yaml_dq "${TLS_MODE}")
  k3s_version: "v1.30.4+k3s1"
  k3s_server_host: "${DEPLOYMENT_TIER}-server"
  k3s_cluster_cidr: "10.42.0.0/16"
  k3s_service_cidr: "10.43.0.0/16"
  digitafrica_namespace: "digitafrica"
  jupyterhub:
    jupyter_nodeport: 30888
    jupyterhub_http_port: 8000
    jupyterhub_admin_users:
      - $(yaml_dq "${ADMIN_USER}")
    jupyterhub_public_url: $(yaml_dq "${scheme}://${PUBLIC_HOST}/jupyter")
    storage_class: $(yaml_dq "${STORAGE_CLASS}")
  mlflow:
    enabled: false
    mlflow_port: 5000
    mlflow_backend_store: "/opt/digitafrica/mlflow/backend"
    mlflow_artifact_root: "/opt/digitafrica/mlflow/artifacts"
    mlflow_auth: false
  grafana_enabled: false
EOF_VARIABLES

  # Derive one workshop client identity per configured worker VM.  The names
  # match the inventory aliases written by write_inventory().
  printf '\nfl_workshop_client_hosts:\n' >> "$VARS_FILE"

  local worker_index
  for worker_index in "${!WORKER_HOSTS[@]}"; do
    printf '  - %s-worker-%s\n' \
      "$DEPLOYMENT_TIER" "$((worker_index + 1))" >> "$VARS_FILE"
  done

  case "$TLS_MODE" in
    letsencrypt)
      printf '  tls_acme_email: %s\n' \
        "$(yaml_dq "${TLS_ACME_EMAIL}")" >> "$VARS_FILE"
      ;;
    provided)
      printf '  tls_cert_dir: %s\n' \
        "$(yaml_dq "${TLS_CERT_DIR}")" >> "$VARS_FILE"
      ;;
  esac

  if [[ "$IDENTITY_ENABLED" == "true" ]]; then
    cat >> "$VARS_FILE" <<EOF_IDENTITY

  identity:
    enabled: true
    namespace: $(yaml_dq "${KEYCLOAK_NAMESPACE}")
    realm: $(yaml_dq "${KEYCLOAK_REALM}")
    admin_user: $(yaml_dq "${KEYCLOAK_ADMIN_USER}")
    bootstrap_admin_password_file: $(yaml_dq "${KEYCLOAK_ADMIN_PASSWORD_FILE}")
    keycloak_public_url: $(yaml_dq "${scheme}://${PUBLIC_HOST}/keycloak")
    postgres_storage_class: $(yaml_dq "${STORAGE_CLASS}")
    postgres_storage_size: "10Gi"
EOF_IDENTITY
  fi

  cat >> "$VARS_FILE" <<EOF_OIDC

oidc:
  oidc_enabled: ${IDENTITY_ENABLED}
  oidc_issuer_url: $(yaml_dq "${IDENTITY_ENABLED}" \
    && printf '%s' "${scheme}://${PUBLIC_HOST}/keycloak/realms/${KEYCLOAK_REALM}" \
    || printf '')
  oidc_client_id: $(yaml_dq "${IDENTITY_ENABLED}" \
    && printf 'jupyterhub' || printf '')
  oidc_scope:
    - "openid"
    - "profile"
    - "email"
  oidc_username_claim: "preferred_username"
  oidc_groups_claim: "groups"
  oidc_tls_verify: ${IDENTITY_ENABLED}
EOF_OIDC

  chmod 600 "$VARS_FILE"
}

run_managed_oidc_deployment() {
  local keycloak_url jupyterhub_url secret_root

  keycloak_url="https://${PUBLIC_HOST}/keycloak"
  jupyterhub_url="https://${PUBLIC_HOST}/jupyter"
  secret_root="${REPO_ROOT}/secrets/keycloak/${PUBLIC_HOST}/${KEYCLOAK_REALM}"

  DIGITAFRICA_INVENTORY="$INVENTORY" \
    "$DEPLOY_SCRIPT" "$DEPLOYMENT_TIER" identity

  KEYCLOAK_ADMIN_PASSWORD_FILE="$KEYCLOAK_ADMIN_PASSWORD_FILE" \
    "$KEYCLOAK_BOOTSTRAP" \
      --server-url "$keycloak_url" \
      --realm "$KEYCLOAK_REALM" \
      --admin-user "$KEYCLOAK_ADMIN_USER" \
      --realm-manager-secret-output \
        "${secret_root}/realm-manager-client.secret" \
      --jupyterhub-client-id "jupyterhub" \
      --jupyterhub-secret-output \
        "${secret_root}/jupyterhub-client.secret" \
      --jupyterhub-redirect-uri \
        "${jupyterhub_url}/hub/oauth_callback" \
      --jupyterhub-web-origin "https://${PUBLIC_HOST}"

  DIGITAFRICA_INVENTORY="$INVENTORY" \
    "$DEPLOY_SCRIPT" "$DEPLOYMENT_TIER" applications
}

run_deployment() {
  if [[ "$IDENTITY_ENABLED" == "true" ]]; then
    run_managed_oidc_deployment
  else
    DIGITAFRICA_INVENTORY="$INVENTORY" \
      "$DEPLOY_SCRIPT" "$DEPLOYMENT_TIER" full
  fi

  if confirm "Run the read-only health check now?"; then
    DIGITAFRICA_INVENTORY="$INVENTORY" \
    DIGITAFRICA_DEPLOYMENT_GROUP="${DEPLOYMENT_TIER}_server" \
      "$HEALTH_SCRIPT" all
  fi
}

show_summary() {
  printf '\nDeployment tier : %s\n' "$DEPLOYMENT_TIER"
  printf 'Profile         : %s\n' "$PROFILE"
  printf 'Central server  : %s\n' "$CENTRAL_HOST"
  printf 'Public host     : %s\n' "$PUBLIC_HOST"
  printf 'TLS mode        : %s\n' "$TLS_MODE"
  printf 'Inventory       : %s\n' "$INVENTORY"
  printf 'Variables       : %s\n' "$VARS_FILE"

  if [[ "$IDENTITY_ENABLED" == "true" ]]; then
    printf 'Keycloak URL    : https://%s/keycloak\n' "$PUBLIC_HOST"
    printf 'JupyterHub URL  : https://%s/jupyter\n' "$PUBLIC_HOST"
  fi
}

main() {
  case "${1:-}" in
    --deploy)
      RUN_DEPLOYMENT="true"
      ;;
    ""|--configure)
      ;;
    -h|--help|help)
      usage
      exit 0
      ;;
    *)
      usage >&2
      die "Unknown option: $1"
      ;;
  esac

  cd "$REPO_ROOT"
  check_prerequisites
  choose_deployment_tier
  choose_profile
  collect_topology
  check_ssh_access
  prepare_keycloak_admin_password

  if ! confirm "Write the local ${DEPLOYMENT_TIER} configuration?"; then
    info "No files were written."
    exit 0
  fi

  ensure_local_git_exclude
  write_inventory
  write_variables
  show_summary

  if [[ "$RUN_DEPLOYMENT" == "true" ]] &&
     confirm "Start the selected deployment now?"; then
    run_deployment
  fi
}

main "$@"
