#!/usr/bin/env bash
# Configure a local DIGITAfrica federated-learning workshop deployment.
#
# Tier-1 creates the local workshop baseline. Tier-2 preserves that baseline
# and adds an overlay [tier2_agents] group. Neither mode modifies repository
# example or production configuration.
#
# Usage:
#   ./scripts/admin/setup-wizard.sh

set -Eeuo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/../.." && pwd)"
WORKSHOP_DIR="${REPO_ROOT}/inventories/workshop"
INVENTORY="${WORKSHOP_DIR}/hosts.ini"
VARS_DIR="${WORKSHOP_DIR}/group_vars"
VARS_FILE="${VARS_DIR}/all.yml"
DEPLOY_SCRIPT="${SCRIPT_DIR}/deploy-infrastructure.sh"
HEALTH_SCRIPT="${SCRIPT_DIR}/health-check.sh"

CENTRAL_HOST=""
PUBLIC_HOST=""
WORKSHOP_TIMEZONE="${WORKSHOP_TIMEZONE:-Europe/Amsterdam}"
SSH_USER="adam"
ADMIN_USER="admin"
WORKER_HOSTS=()
PROFILE=""
DEPLOYMENT_TIER=""
TLS_MODE="selfsigned"
TLS_CERT_DIR=""
TLS_ACME_EMAIL=""
OIDC_ENABLED="false"
OIDC_ISSUER_URL=""
OIDC_CLIENT_ID=""
OIDC_CLIENT_SECRET=""
STORAGE_CLASS="local-path"

colour() {
  local code="$1"
  shift
  if [ -t 1 ]; then
    printf '\033[%sm%s\033[0m\n' "${code}" "$*"
  else
    printf '%s\n' "$*"
  fi
}

heading() { colour '1;36' "$*"; }
info() { colour '0;32' "[OK] $*"; }
warn() { colour '0;33' "[WARNING] $*" >&2; }
error() { colour '0;31' "[ERROR] $*" >&2; }
die() { error "$*"; exit 1; }

on_error() {
  local line="$1"
  error "The wizard stopped at line ${line}. No deployment was started."
}
trap 'on_error "$LINENO"' ERR

usage() {
  cat <<'EOF'
Usage: scripts/admin/setup-wizard.sh

Creates or updates a local workshop inventory and configuration in:
  inventories/workshop/hosts.ini
  inventories/workshop/group_vars/all.yml

Choose Tier-1 to create a workshop baseline. Choose Tier-2 only after that
baseline exists; it preserves Tier-1 settings and replaces [tier2_agents].
These files are locally excluded from Git. The wizard can optionally run the
corresponding deployment and health-check workflows afterwards.
EOF
}

require_command() {
  command -v "$1" >/dev/null 2>&1 || die "Required command not found: $1"
}

confirm() {
  local prompt="$1"
  local answer
  read -r -p "${prompt} [y/N]: " answer
  [[ "${answer}" =~ ^[Yy]([Ee][Ss])?$ ]]
}

prompt_required() {
  local variable_name="$1"
  local prompt="$2"
  local default_value="${3:-}"
  local value

  while true; do
    if [ -n "${default_value}" ]; then
      read -r -p "${prompt} [${default_value}]: " value
      value="${value:-${default_value}}"
    else
      read -r -p "${prompt}: " value
    fi

    if [ -n "${value}" ]; then
      printf -v "${variable_name}" '%s' "${value}"
      return 0
    fi
    warn "A value is required."
  done
}

prompt_choice() {
  local variable_name="$1"
  local prompt="$2"
  local default_value="$3"
  shift 3
  local -a allowed=("$@")
  local value

  while true; do
    read -r -p "${prompt} [${default_value}]: " value
    value="${value:-${default_value}}"
    for candidate in "${allowed[@]}"; do
      if [ "${value}" = "${candidate}" ]; then
        printf -v "${variable_name}" '%s' "${value}"
        return 0
      fi
    done
    warn "Choose one of: ${allowed[*]}"
  done
}

validate_host() {
  # Supports ordinary hostnames, IPv4 addresses and simple IPv6 literals.
  [[ "$1" =~ ^[A-Za-z0-9][A-Za-z0-9._:-]*$ ]]
}

validate_identifier() {
  [[ "$1" =~ ^[A-Za-z_][A-Za-z0-9_.-]*$ ]]
}

validate_host_or_die() {
  validate_host "$1" || die "Invalid host value: $1"
}

yaml_dq() {
  local value="$1"
  value="${value//\\/\\\\}"
  value="${value//\"/\\\"}"
  value="${value//$'\n'/}"
  printf '"%s"' "${value}"
}

ensure_local_git_exclude() {
  local exclude_file
  local pattern='inventories/workshop/'

  if ! git -C "${REPO_ROOT}" rev-parse --is-inside-work-tree >/dev/null 2>&1; then
    warn "Repository is not a Git working tree; local workshop files are not automatically ignored."
    return 0
  fi

  exclude_file="$(git -C "${REPO_ROOT}" rev-parse --git-path info/exclude)"
  case "${exclude_file}" in
    /*) ;;
    *) exclude_file="${REPO_ROOT}/${exclude_file}" ;;
  esac
  mkdir -p "$(dirname "${exclude_file}")"
  touch "${exclude_file}"

  if ! grep -Fqx "${pattern}" "${exclude_file}"; then
    printf '\n# Local configuration generated by scripts/admin/setup-wizard.sh\n%s\n' \
      "${pattern}" >> "${exclude_file}"
  fi
}

check_prerequisites() {
  heading "Checking control-machine prerequisites"
  require_command ssh
  require_command ansible
  require_command ansible-playbook
  require_command git
  [ -f "${REPO_ROOT}/playbooks/tier1.yml" ] || die "Tier-1 playbook not found. Run the wizard from a complete repository checkout."
  [ -f "${REPO_ROOT}/playbooks/tier2.yml" ] || die "Tier-2 playbook not found. Run the wizard from a complete repository checkout."
  [ -x "${DEPLOY_SCRIPT}" ] || die "Deployment helper is missing or not executable: ${DEPLOY_SCRIPT}"
  [ -x "${HEALTH_SCRIPT}" ] || die "Health-check helper is missing or not executable: ${HEALTH_SCRIPT}"
  info "ssh, Ansible and repository deployment helpers are available."
}

choose_deployment_tier() {
  heading "Choose deployment tier"
  cat <<'EOF'

  1) Tier-1 baseline
     Creates or replaces the local workshop inventory and configuration.

  2) Tier-2 overlay
     Requires an existing local Tier-1 workshop inventory. Preserves its
     Tier-1 hosts and variables, then adds or replaces [tier2_agents].
EOF
  prompt_choice DEPLOYMENT_TIER "Deployment tier" "1" 1 2
  if [ "${DEPLOYMENT_TIER}" = "1" ]; then
    DEPLOYMENT_TIER="tier1"
  else
    DEPLOYMENT_TIER="tier2"
  fi
}

choose_profile() {
  heading "Choose deployment profile"
  cat <<'EOF'

  1) Basic workshop (recommended)
     Direct IP/hostname access, self-signed TLS, JupyterHub dummy login,
     and local-path storage. No DNS, external identity provider or shared
     storage is required.

  2) Advanced deployment
     Lets you choose TLS, optional OIDC authentication and storage class.
EOF
  prompt_choice PROFILE "Profile" "1" 1 2

  if [ "${PROFILE}" = "1" ]; then
    TLS_MODE="selfsigned"
    OIDC_ENABLED="false"
    STORAGE_CLASS="local-path"
    return 0
  fi

  heading "Advanced options"
  echo "TLS mode: 1) self-signed  2) Let's Encrypt  3) provided certificate  4) none"
  local tls_choice
  prompt_choice tls_choice "TLS mode" "1" 1 2 3 4
  case "${tls_choice}" in
    1) TLS_MODE="selfsigned" ;;
    2)
      TLS_MODE="letsencrypt"
      prompt_required TLS_ACME_EMAIL "ACME registration email"
      ;;
    3)
      TLS_MODE="provided"
      prompt_required TLS_CERT_DIR "Control-machine directory containing tls.crt and tls.key"
      [ -f "${TLS_CERT_DIR}/tls.crt" ] || die "Missing ${TLS_CERT_DIR}/tls.crt"
      [ -f "${TLS_CERT_DIR}/tls.key" ] || die "Missing ${TLS_CERT_DIR}/tls.key"
      ;;
    4) TLS_MODE="none" ;;
  esac

  if confirm "Enable Keycloak/OpenID Connect authentication?"; then
    OIDC_ENABLED="true"
    prompt_required OIDC_ISSUER_URL "OIDC issuer URL"
    prompt_required OIDC_CLIENT_ID "OIDC client ID"
    read -r -s -p "OIDC client secret: " OIDC_CLIENT_SECRET
    printf '\n'
    [ -n "${OIDC_CLIENT_SECRET}" ] || die "An OIDC client secret is required when OIDC is enabled."
  fi

  prompt_required STORAGE_CLASS "Kubernetes StorageClass" "local-path"
}

collect_topology() {
  heading "Workshop topology"
  echo "Enter the address used by Ansible to reach each VM."
  prompt_required CENTRAL_HOST "Central Tier-1 server hostname or IP"
  validate_host_or_die "${CENTRAL_HOST}"

  prompt_required SSH_USER "SSH username" "adam"
  validate_identifier "${SSH_USER}" || die "Invalid SSH username: ${SSH_USER}"

  # The current bundled Tier-1 Flower bootstrap has intentional references to
  # /home/adam and owner/group adam. Do not pretend that another account works.
  if [ "${SSH_USER}" != "adam" ]; then
    die "This repository's current Tier-1 Flower bootstrap is tied to the Linux account 'adam' (/home/adam). Use adam, or first generalise playbooks/tier1.yml."
  fi

  prompt_required ADMIN_USER "JupyterHub administrator username" "admin"
  validate_identifier "${ADMIN_USER}" || die "Invalid JupyterHub administrator username: ${ADMIN_USER}"

  local workers_line worker
  while true; do
    read -r -p "Worker VM hostnames or IPs (space-separated; at least one): " workers_line
    read -r -a WORKER_HOSTS <<< "${workers_line}"
    [ "${#WORKER_HOSTS[@]}" -gt 0 ] || { warn "At least one worker is required for the workshop profile."; continue; }

    for worker in "${WORKER_HOSTS[@]}"; do
      validate_host "${worker}" || die "Invalid worker host value: ${worker}"
      [ "${worker}" != "${CENTRAL_HOST}" ] || die "A worker cannot be the same as the central server."
    done
    break
  done

  prompt_required PUBLIC_HOST "Public JupyterHub hostname or IP" "${CENTRAL_HOST}"
  validate_host_or_die "${PUBLIC_HOST}"

  prompt_required WORKSHOP_TIMEZONE "Timezone for the workshop VMs" "${WORKSHOP_TIMEZONE}"
}

collect_tier2_topology() {
  heading "Tier-2 overlay topology"

  [ -f "${INVENTORY}" ] || die \
    "Tier-2 requires an existing local Tier-1 inventory: ${INVENTORY}. Run the wizard in Tier-1 mode first."
  [ -f "${VARS_FILE}" ] || die \
    "Tier-2 requires existing local Tier-1 variables: ${VARS_FILE}. Run the wizard in Tier-1 mode first."

  CENTRAL_HOST="$(awk '
    /^\[tier1_server\]$/ { in_group=1; next }
    /^\[/ { in_group=0 }
    in_group && $0 !~ /^[[:space:]]*([#;]|$)/ {
      for (i = 1; i <= NF; i++) {
        if ($i ~ /^ansible_host=/) {
          sub(/^ansible_host=/, "", $i)
          print $i
          exit
        }
      }
    }
  ' "${INVENTORY}")"
  [ -n "${CENTRAL_HOST}" ] || die \
    "Could not read an ansible_host from [tier1_server] in ${INVENTORY}."

  local tier1_worker_count
  tier1_worker_count="$(awk '
    /^\[tier1_agents\]$/ { in_group=1; next }
    /^\[/ { in_group=0 }
    in_group && $0 !~ /^[[:space:]]*([#;]|$)/ { count++ }
    END { print count + 0 }
  ' "${INVENTORY}")"
  [ "${tier1_worker_count}" -gt 0 ] || die \
    "Tier-2 requires one or more hosts in [tier1_agents] in ${INVENTORY}."

  SSH_USER="$(awk -F= '
    /^ansible_user=/ { print $2; exit }
  ' "${INVENTORY}")"
  SSH_USER="${SSH_USER:-adam}"
  validate_identifier "${SSH_USER}" || die \
    "Invalid ansible_user in existing inventory: ${SSH_USER}"

  printf 'Existing Tier-1 central server : %s\n' "${CENTRAL_HOST}"
  printf 'Existing Tier-1 worker count   : %s\n' "${tier1_worker_count}"
  printf 'Existing SSH user              : %s\n' "${SSH_USER}"

  local workers_line worker
  while true; do
    read -r -p "New Tier-2 worker VM hostnames or IPs (space-separated; at least one): " workers_line
    read -r -a WORKER_HOSTS <<< "${workers_line}"
    [ "${#WORKER_HOSTS[@]}" -gt 0 ] || {
      warn "At least one Tier-2 worker is required."
      continue
    }

    for worker in "${WORKER_HOSTS[@]}"; do
      validate_host "${worker}" || die "Invalid worker host value: ${worker}"
      [ "${worker}" != "${CENTRAL_HOST}" ] || die \
        "A Tier-2 worker cannot be the same as the central server."
    done

    if [ "$(printf '%s\n' "${WORKER_HOSTS[@]}" | sort -u | wc -l)" \
      -ne "${#WORKER_HOSTS[@]}" ]; then
      warn "Each Tier-2 worker must be listed only once."
      continue
    fi
    break
  done
}

check_ssh_access() {
  heading "Checking SSH access"
  local host
  local -a hosts=("${CENTRAL_HOST}" "${WORKER_HOSTS[@]}")

  for host in "${hosts[@]}"; do
    printf 'Checking %s@%s ... ' "${SSH_USER}" "${host}"
    if ssh \
      -o BatchMode=yes \
      -o ConnectTimeout=10 \
      -o StrictHostKeyChecking=accept-new \
      "${SSH_USER}@${host}" true; then
      printf 'OK\n'
    else
      printf 'FAILED\n'
      cat >&2 <<EOF
SSH key authentication failed for ${SSH_USER}@${host}.

Add the public key of this Ansible control machine to that VM's:
  /home/${SSH_USER}/.ssh/authorized_keys

Do not copy a private key to the VM. Fix SSH access and run the wizard again.
EOF
      exit 1
    fi
  done
  info "SSH key authentication works for the central server and all workers."
}

write_inventory() {
  mkdir -p "${VARS_DIR}"
  cat > "${INVENTORY}" <<EOF
# Generated by scripts/admin/setup-wizard.sh. Do not commit this local file.
[tier1_server]
tier1-server ansible_host=${CENTRAL_HOST}

[tier1_agents]
EOF

  local index=1
  local worker
  for worker in "${WORKER_HOSTS[@]}"; do
    printf 'tier1-worker-%s ansible_host=%s\n' "${index}" "${worker}" >> "${INVENTORY}"
    index=$((index + 1))
  done

  cat >> "${INVENTORY}" <<EOF

[all:vars]
ansible_user=${SSH_USER}
ansible_become=true
EOF
}

write_tier2_inventory() {
  python3 - "${INVENTORY}" "${WORKER_HOSTS[@]}" <<'PY2'
import re
import sys
from pathlib import Path

inventory_path = Path(sys.argv[1])
tier2_hosts = sys.argv[2:]
text = inventory_path.read_text()

if not re.search(r"(?m)^\[tier1_server\]\s*$", text):
    raise SystemExit("Existing workshop inventory has no [tier1_server] group.")
if not re.search(r"(?m)^\[tier1_agents\]\s*$", text):
    raise SystemExit("Existing workshop inventory has no [tier1_agents] group.")
if not re.search(r"(?m)^\[all:vars\]\s*$", text):
    raise SystemExit("Existing workshop inventory has no [all:vars] group.")

tier2_section = re.compile(r"(?ms)^\[tier2_agents\]\s*\n.*?(?=^\[|\Z)")
text_without_tier2 = tier2_section.sub("", text)

existing_hosts = set(
    re.findall(r"(?m)\bansible_host=([^\s#;]+)", text_without_tier2)
)
duplicates = sorted(set(tier2_hosts) & existing_hosts)
if duplicates:
    raise SystemExit(
        "Tier-2 worker address already belongs to the Tier-1 baseline: "
        + ", ".join(duplicates)
    )

section = "[tier2_agents]\n" + "".join(
    f"tier2-worker-{index} ansible_host={host}\n"
    for index, host in enumerate(tier2_hosts, start=1)
) + "\n"

anchor = re.search(r"(?m)^\[all:vars\]\s*$", text_without_tier2)
text = (
    text_without_tier2[:anchor.start()]
    + section
    + text_without_tier2[anchor.start():]
)
inventory_path.write_text(text)
PY2
}

write_variables() {
  local scheme="https"
  [ "${TLS_MODE}" = "none" ] && scheme="http"

  cat > "${VARS_FILE}" <<EOF
# Generated by scripts/admin/setup-wizard.sh. Do not commit this local file.
# Profile: $([ "${PROFILE}" = "1" ] && printf 'basic workshop' || printf 'advanced')
timezone: "${WORKSHOP_TIMEZONE}"

tier1:
  expose_mode: "ingress"
  tls_mode: "${TLS_MODE}"
  k3s_version: "v1.30.4+k3s1"
  k3s_server_host: "tier1-server"
  k3s_cluster_cidr: "10.42.0.0/16"
  k3s_service_cidr: "10.43.0.0/16"
  digitafrica_namespace: "digitafrica"
  jupyterhub:
    jupyter_nodeport: 30888
    jupyterhub_http_port: 8000
    jupyterhub_admin_users:
      - $(yaml_dq "${ADMIN_USER}")
    jupyterhub_public_url: $(yaml_dq "${scheme}://${PUBLIC_HOST}/jupyter")
    storage_class: $(yaml_dq "${STORAGE_CLASS}")
  mlflow:
    enabled: false
    mlflow_port: 5000
    mlflow_backend_store: "/opt/digitafrica/mlflow/backend"
    mlflow_artifact_root: "/opt/digitafrica/mlflow/artifacts"
    mlflow_auth: false
  grafana_enabled: false
EOF

  case "${TLS_MODE}" in
    letsencrypt)
      printf '  tls_acme_email: %s\n' "$(yaml_dq "${TLS_ACME_EMAIL}")" >> "${VARS_FILE}"
      ;;
    provided)
      printf '  tls_cert_dir: %s\n' "$(yaml_dq "${TLS_CERT_DIR}")" >> "${VARS_FILE}"
      ;;
  esac

  cat >> "${VARS_FILE}" <<EOF

oidc:
  oidc_enabled: ${OIDC_ENABLED}
EOF

  if [ "${OIDC_ENABLED}" = "true" ]; then
    cat >> "${VARS_FILE}" <<EOF
  oidc_issuer_url: $(yaml_dq "${OIDC_ISSUER_URL}")
  oidc_client_id: $(yaml_dq "${OIDC_CLIENT_ID}")
  oidc_client_secret: $(yaml_dq "${OIDC_CLIENT_SECRET}")
  oidc_scope:
    - "openid"
    - "profile"
    - "email"
  oidc_username_claim: "preferred_username"
  oidc_tls_verify: true
EOF
    chmod 600 "${VARS_FILE}"
  else
    cat >> "${VARS_FILE}" <<'EOF'
  oidc_issuer_url: ""
  oidc_client_id: ""
  oidc_client_secret: ""
  oidc_scope:
    - "openid"
    - "profile"
    - "email"
  oidc_username_claim: "preferred_username"
  oidc_tls_verify: false
EOF
  fi
}

show_summary() {
  heading "Workshop deployment summary"
  printf 'Deployment tier     : %s\n' "${DEPLOYMENT_TIER}"
  printf 'Central k3s server  : %s\n' "${CENTRAL_HOST}"
  printf 'New worker nodes    : %s\n' "${#WORKER_HOSTS[@]}"
  printf 'SSH user            : %s\n' "${SSH_USER}"
  printf 'Inventory           : %s\n' "${INVENTORY}"

  if [ "${DEPLOYMENT_TIER}" = "tier2" ]; then
    printf 'Tier-1 variables    : %s (preserved)\n' "${VARS_FILE}"
    return 0
  fi

  printf 'JupyterHub URL      : %s://%s/jupyter/\n' \
    "$([ "${TLS_MODE}" = "none" ] && printf http || printf https)" "${PUBLIC_HOST}"
  printf 'TLS                 : %s\n' "${TLS_MODE}"
  printf 'Authentication      : %s\n' \
    "$([ "${OIDC_ENABLED}" = true ] && printf OIDC || printf 'workshop dummy login')"
  printf 'Storage class       : %s\n' "${STORAGE_CLASS}"
  printf 'Variables           : %s\n' "${VARS_FILE}"

  if [ "${TLS_MODE}" = "selfsigned" ]; then
    warn "Participants will see a browser certificate warning. Verify the URL with them before they continue."
  fi
  if [ "${OIDC_ENABLED}" = "false" ]; then
    warn "Dummy login is suitable only for a controlled workshop, not for sensitive data or open access."
  fi
}

run_optional_actions() {
  if ! confirm "Run the ${DEPLOYMENT_TIER} deployment now?"; then
    echo
    echo "Configuration is ready. Deploy later with:"
    printf '  DIGITAFRICA_INVENTORY=%q %q %s\n' \
      "${INVENTORY}" "${DEPLOY_SCRIPT}" "${DEPLOYMENT_TIER}"
    return 0
  fi

  DIGITAFRICA_INVENTORY="${INVENTORY}" \
    "${DEPLOY_SCRIPT}" "${DEPLOYMENT_TIER}"

  if confirm "Run the read-only health check now?"; then
    DIGITAFRICA_INVENTORY="${INVENTORY}" "${HEALTH_SCRIPT}" all
  fi
}

main() {
  case "${1:-}" in
    help|--help|-h)
      usage
      return 0
      ;;
    "")
      ;;
    *)
      usage >&2
      die "Unknown option: $1"
      ;;
  esac

  cd "${REPO_ROOT}"
  heading "DIGITAfrica Edge-AI workshop setup wizard"
  echo "This wizard configures either a Tier-1 baseline or a Tier-2 overlay."
  echo

  check_prerequisites
  choose_deployment_tier

  if [ "${DEPLOYMENT_TIER}" = "tier1" ]; then
    choose_profile
    collect_topology
  else
    collect_tier2_topology
  fi
  check_ssh_access

  if ! confirm "Write the local workshop configuration?"; then
    echo "No files were written."
    return 0
  fi

  ensure_local_git_exclude
  if [ "${DEPLOYMENT_TIER}" = "tier1" ]; then
    write_inventory
    write_variables
    info "Generated local Tier-1 workshop inventory and variables."
  else
    write_tier2_inventory
    info "Updated local workshop inventory with Tier-2 workers; Tier-1 variables were preserved."
  fi

  show_summary
  run_optional_actions
}

main "$@"
