- name: Install k3s server
  ansible.builtin.shell: |
    curl -sfL https://get.k3s.io | INSTALL_K3S_VERSION="{{ digitafrica_deployment.k3s_version }}" sh -s - server \
      --write-kubeconfig-mode 644 \
      --cluster-cidr "{{ digitafrica_deployment.k3s_cluster_cidr }}" \
      --service-cidr "{{ digitafrica_deployment.k3s_service_cidr }}" \
      {% if digitafrica_deployment.expose_mode == 'ingress' %} --disable servicelb {% endif %} \
      {% if digitafrica_deployment.expose_mode != 'ingress' %} --disable traefik {% endif %}
  args:
    creates: /usr/local/bin/k3s

- name: Read k3s node token
  ansible.builtin.slurp:
    src: /var/lib/rancher/k3s/server/node-token
  register: k3s_token

- name: Set fact with decoded token
  ansible.builtin.set_fact:
    k3s_node_token_decoded: "{{ k3s_token.content | b64decode | trim }}"
