# Common
timezone: "Europe/Athens"


tier0:
  k3s_mode: "none"   # none|agent|single
  expose_mode: "ingress"      # nodeport|ingress  (set to nodeport to fall back to NodePort)
  notebook_port: 8888 # port for local jupyter books to expose 
  jupyter_nodeport: 30888 # port to expose if not using ingress
  modelcache_nodeport: 30080 #port to expose if not using ingress
  notebook_user: "digitafrica"
  notebook_dir: "/opt/digitafrica/notebooks"
  notebook_password: "digitafrica"   # you can swap to token-only
  notebook_password_hash: "argon2:$argon2id$v=19$m=10240,t=10,p=8$9f4c5S6aMZ5sKSI2sBpHWg$tBmHxYwRPIxqjssK5LrgO/TiGTHLATRxossGnK5hEks"
  enable_modelcache: true
  digitafrica_namespace: "digitafrica"
  # k3s config for tier0's single node cluster (mode=single)
  k3s_version: "v1.30.4+k3s1"
  # Used only when k3s_mode=agent — tier0 joins this tier1 server
  k3s_agent_server_host: "digitafrica-edge-node1"
  k3s_agent_version: "v1.30.4+k3s1"
  monitoring:
    node_exporter_port: 9100
    cadvisor_port: 8080

tier1:
  expose_mode: "ingress"   # ingress = deploy Traefik Ingress | nodeport = no Traefik, services use NodePort
  tls_mode: "selfsigned"   # selfsigned | letsencrypt | provided | none  (ignored when expose_mode=nodeport)
  # tls_cert_dir: "/path/to/local/certs"   # only when tls_mode=provided — local dir containing tls.crt and tls.key
  # tls_acme_email: "admin@example.com"    # only when tls_mode=letsencrypt
  k3s_version: "v1.30.4+k3s1"
  k3s_server_host: "digitafrica-edge-node1"
  k3s_cluster_cidr: "10.42.0.0/16"
  k3s_service_cidr: "10.43.0.0/16"
  digitafrica_namespace: "digitafrica"
  jupyterhub:
    jupyter_nodeport: 30888
    jupyterhub_http_port: 8000
    jupyterhub_admin_users: ["admin"]
    jupyterhub_public_url: "https://10.64.45.176/jupyter"
    storage_class: "local-path"   # switch to your NFS class (e.g. nfs-client) for multi-node freedom
  mlflow:
    enabled: false         # not tested yet
    mlflow_port: 5000
    mlflow_backend_store: "/opt/digitafrica/mlflow/backend"   # sqlite by default
    mlflow_artifact_root: "/opt/digitafrica/mlflow/artifacts" # local FS
    mlflow_auth: false  # not tested yet
  grafana_enabled: false   # not tested yet

# OIDC / Keycloak
oidc: 
  oidc_enabled: false
  oidc_issuer_url: "https://auth.theblueprintfactory.org:8080/realms/slices-test"
  oidc_client_id: "jupyterhub-client"
  oidc_client_secret: "ERm5yMzbtGUDTJ5IuA09MxUUH8NgZBI2"
  oidc_scope:
    - "openid"
    - "profile"
    - "email"
  oidc_username_claim: "preferred_username"
  oidc_tls_verify: false 
