#!/usr/bin/env bash
# Create/reconcile one Keycloak participant identity and group per active workshop worker.
# New passwords are written only to the requested mode-0600 credentials file.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/../.." && pwd)"
WORKSHOP_CONTEXT="$SCRIPT_DIR/workshop-context.sh"

DEFAULT_REALM="digitafrica"
DEFAULT_GROUP_PREFIX="group_"

inventory=""
worker_group=""
server_url=""
realm="${DEFAULT_REALM}"
group_prefix="${DEFAULT_GROUP_PREFIX}"
credentials_output=""
admin_realm=""
admin_client_id=""
admin_client_secret_file=""
admin_user=""
password_file="${KEYCLOAK_ADMIN_PASSWORD_FILE:-}"
dry_run=false
reset_password_for=""
reset_all_passwords=false
delete_all_participants=false
create_missing=false

usage() {
  cat <<'EOF'
Usage:
  create-participant-accounts.sh --server-url URL [--credentials-output FILE] \
    [--realm NAME] [options]

Creates or reconciles one Keycloak user and group per worker in the active
workshop release record. Workers yield identities group_01, group_02, ... .
Each identity is added to the matching Keycloak group of the same name.

Required:
  --server-url URL             Public Keycloak base URL, e.g. https://host/keycloak
  --credentials-output FILE    New mode-0600 TSV file for credentials generated by this run
                             Required unless --delete-all-participants is used

Workshop identity options:
  --realm NAME                 Keycloak participant realm (default: digitafrica)
  --group-prefix PREFIX        Account/group prefix (default: group_)

Authentication: choose one method
  Service account (recommended):
    --admin-client-id ID --admin-client-secret-file FILE [--admin-realm NAME]

  Administrator fallback:
    --admin-user USER [--admin-realm NAME]
    The password is read privately from /dev/tty, unless
    KEYCLOAK_ADMIN_PASSWORD_FILE points to a readable mode-0600 file.

Safety:
  --reset-password-for USER    Reset exactly one existing expected participant account
  --reset-all-passwords        Reset every expected participant account from the inventory
  --create-missing             With --reset-all-passwords, create missing expected users/groups
  --delete-all-participants    Delete inventory-derived users and matching groups
  --dry-run                    Show intended actions without changing Keycloak
  -h, --help                   Show this help

Notes:
  Existing accounts are preserved unless an explicit password-reset option is selected.
  A reset verifies that every selected user and matching Keycloak group exist,
  unless --reset-all-passwords is combined with --create-missing.
  The TSV output contains passwords created or reset by this run only.
EOF
}

fail() { printf '[ERROR] %s\n' "$*" >&2; exit 1; }
info() { printf '[INFO] %s\n' "$*" >&2; }
require_command() { command -v "$1" >/dev/null 2>&1 || fail "Required command not found: $1"; }

require_mode_600() {
  local file="$1" mode
  [[ -r "${file}" ]] || fail "Credential file is not readable: ${file}"
  mode="$(stat -c '%a' "${file}" 2>/dev/null || stat -f '%Lp' "${file}")"
  [[ "${mode}" == "600" ]] || fail "Credential file must have mode 0600: ${file} (found ${mode})"
}

urlencode() { jq -rn --arg value "$1" '$value|@uri'; }

while [[ $# -gt 0 ]]; do
  case "$1" in
    --server-url) server_url="${2:-}"; shift 2 ;;
    --realm) realm="${2:-}"; shift 2 ;;
    --group-prefix) group_prefix="${2:-}"; shift 2 ;;
    --credentials-output) credentials_output="${2:-}"; shift 2 ;;
    --admin-realm) admin_realm="${2:-}"; shift 2 ;;
    --admin-client-id) admin_client_id="${2:-}"; shift 2 ;;
    --admin-client-secret-file) admin_client_secret_file="${2:-}"; shift 2 ;;
    --admin-user) admin_user="${2:-}"; shift 2 ;;
    --reset-password-for) reset_password_for="${2:-}"; shift 2 ;;
    --reset-all-passwords) reset_all_passwords=true; shift ;;
    --delete-all-participants) delete_all_participants=true; shift ;;
    --create-missing) create_missing=true; shift ;;
    --dry-run) dry_run=true; shift ;;
    -h|--help) usage; exit 0 ;;
    *) fail "Unknown argument: $1" ;;
  esac
done

[[ -r "$WORKSHOP_CONTEXT" ]] ||
  fail "Missing workshop context helper: $WORKSHOP_CONTEXT"
# shellcheck source=workshop-context.sh
source "$WORKSHOP_CONTEXT"
load_workshop_context || exit 1

inventory="$DIGITAFRICA_INVENTORY"
worker_group="$DIGITAFRICA_DEPLOYMENT_WORKER_GROUP"

# Service-account clients belong to the workshop realm.  Human Keycloak
# administrators normally authenticate in the master realm.
if [[ -z "${admin_realm}" ]]; then
  if [[ -n "${admin_client_id}${admin_client_secret_file}" ]]; then
    admin_realm="${realm}"
  else
    admin_realm="master"
  fi
fi

require_command ansible-inventory
require_command curl
require_command jq
require_command python3
[[ -n "${server_url}" ]] || fail "--server-url is required"
[[ "${delete_all_participants}" == true || -n "${credentials_output}" ]] || \
  fail "--credentials-output is required unless --delete-all-participants is used"
[[ -f "${inventory}" ]] || fail "Inventory not found: ${inventory}"
[[ "${server_url}" =~ ^https:// ]] || fail "--server-url must use https://"
[[ "${group_prefix}" =~ ^[A-Za-z0-9_-]+$ ]] || fail "--group-prefix may contain only letters, numbers, _ and -"
[[ -z "${reset_password_for}" || "${reset_password_for}" =~ ^[A-Za-z0-9_-]+$ ]] || \
  fail "--reset-password-for may contain only letters, numbers, _ and -"
[[ ! ( -n "${reset_password_for}" && "${reset_all_passwords}" == true ) ]] || \
  fail "Choose either --reset-password-for or --reset-all-passwords, not both"

if [[ "${delete_all_participants}" == true ]]; then
  [[ -z "${reset_password_for}" ]] || \
    fail "--delete-all-participants cannot be combined with --reset-password-for"
  [[ "${reset_all_passwords}" != true ]] || \
    fail "--delete-all-participants cannot be combined with --reset-all-passwords"
  [[ "${create_missing}" != true ]] || \
    fail "--delete-all-participants cannot be combined with --create-missing"
fi

[[ "${create_missing}" != true || "${reset_all_passwords}" == true ]] || \
  fail "--create-missing requires --reset-all-passwords"

if [[ "${dry_run}" != true ]]; then
  if [[ -n "${admin_client_id}${admin_client_secret_file}" ]]; then
    [[ -n "${admin_client_id}" && -n "${admin_client_secret_file}" ]] || \
      fail "Service-account authentication requires both --admin-client-id and --admin-client-secret-file"
    [[ -z "${admin_user}" ]] || fail "Choose either service-account authentication or --admin-user, not both"
    require_mode_600 "${admin_client_secret_file}"
  elif [[ -n "${admin_user}" ]]; then
    if [[ -n "${password_file}" ]]; then
      require_mode_600 "${password_file}"
    else
      read -r -s -p "Keycloak administrator password for ${admin_user} in realm ${admin_realm}: " admin_password </dev/tty
      printf '\n' >&2
      [[ -n "${admin_password}" ]] || fail "A Keycloak administrator password is required."
    fi
  else
    fail "Choose service-account authentication or supply --admin-user"
  fi
fi

if [[ "${delete_all_participants}" != true && -e "${credentials_output}" ]]; then
  fail "Credentials output already exists; choose a new path to prevent accidental overwrite: ${credentials_output}"
fi

server_url="${server_url%/}"
api_base="${server_url}/admin/realms/${realm}"
inventory_json="$(ansible-inventory -i "${inventory}" --list)"

if ! jq -e --arg group "${worker_group}" 'has($group)' >/dev/null <<<"${inventory_json}"; then
  fail "Worker group '${worker_group}' was not found in ${inventory}"
fi

mapfile -t workers < <(
  jq -r --arg group "${worker_group}" '
    def members($root; $name):
      $root[$name] as $entry |
      ($entry.hosts // [])[],
      (($entry.children // [])[] as $child | members($root; $child));
    [members(.; $group)] | unique[]
  ' <<<"${inventory_json}"
)

[[ ${#workers[@]} -gt 0 ]] || fail "No hosts resolved from inventory group '${worker_group}'"
info "Resolved ${#workers[@]} worker(s) from ${worker_group}: ${workers[*]}"

selected_count="${#workers[@]}"
if [[ -n "${reset_password_for}" ]]; then
  reset_target_known=false
  for index in "${!workers[@]}"; do
    expected_username="$(printf '%s%02d' "${group_prefix}" "$((index + 1))")"
    if [[ "${expected_username}" == "${reset_password_for}" ]]; then
      reset_target_known=true
      break
    fi
  done
  [[ "${reset_target_known}" == true ]] || \
    fail "--reset-password-for must name an expected participant identity: ${reset_password_for}"
  selected_count=1
fi

if [[ "${dry_run}" == true ]]; then
  if [[ "${delete_all_participants}" == true ]]; then
    for index in "${!workers[@]}"; do
      username="$(printf '%s%02d' "${group_prefix}" "$((index + 1))")"
      printf 'Would delete participant user and matching group: %s (worker: %s)\n' \
        "${username}" "${workers[index]}"
    done
    printf 'Dry run complete: %d participant account(s) selected for deletion.\n' "${selected_count}"
    exit 0
  fi

  for index in "${!workers[@]}"; do
    username="$(printf '%s%02d' "${group_prefix}" "$((index + 1))")"
    [[ "${reset_all_passwords}" == true || -z "${reset_password_for}" || "${username}" == "${reset_password_for}" ]] || continue
    if [[ "${reset_all_passwords}" == true || -n "${reset_password_for}" ]]; then
      printf 'Would reset the existing password for: %s (worker: %s)\n' \
        "${username}" "${workers[index]}"
    else
      printf 'Would reconcile user and group: %s (worker: %s)\n' \
        "${username}" "${workers[index]}"
    fi
  done
  printf 'Dry run complete: %d participant account(s) selected.\n' "${selected_count}"
  exit 0
fi

get_token() {
  local endpoint secret
  local -a payload
  endpoint="${server_url}/realms/$(urlencode "${admin_realm}")/protocol/openid-connect/token"
  if [[ -n "${admin_client_id}" ]]; then
    secret="$(<"${admin_client_secret_file}")"
    payload=(--data-urlencode 'grant_type=client_credentials' --data-urlencode "client_id=${admin_client_id}" --data-urlencode "client_secret=${secret}")
  else
    if [[ -n "${password_file}" ]]; then admin_password="$(<"${password_file}")"; fi
    payload=(--data-urlencode 'grant_type=password' --data-urlencode "client_id=admin-cli" --data-urlencode "username=${admin_user}" --data-urlencode "password=${admin_password}")
  fi
  curl --silent --show-error --fail --request POST "${endpoint}" "${payload[@]}" | jq -er '.access_token'
}

access_token="$(get_token)" || fail "Could not obtain a Keycloak administrator access token"
unset admin_password

api() {
  local method="$1" path="$2"; shift 2
  curl --silent --show-error --fail \
    --request "${method}" \
    --header "Authorization: Bearer ${access_token}" \
    --header 'Content-Type: application/json' \
    "${api_base}${path}" "$@"
}


credentials_tmp=""
credential_records=0

cleanup_credentials() {
  local status=$?
  trap - EXIT

  if [[ -n "${credentials_tmp}" && -e "${credentials_tmp}" ]]; then
    if (( credential_records > 0 )); then
      printf '[ERROR] Participant changes may be partial. Recovery credentials retained (mode 0600): %s\n' \
        "${credentials_tmp}" >&2
    else
      rm -f -- "${credentials_tmp}" || true
    fi
  fi

  exit "${status}"
}

if [[ "${delete_all_participants}" != true ]]; then
  credentials_dir="$(dirname "${credentials_output}")"
  credentials_name="$(basename "${credentials_output}")"
  mkdir -p "${credentials_dir}"
  credentials_tmp="$(umask 077; mktemp "${credentials_dir}/.${credentials_name}.failed.XXXXXX")"
  chmod 600 "${credentials_tmp}"
  trap cleanup_credentials EXIT
fi

find_group_id() {
  local name="$1" encoded
  encoded="$(urlencode "${name}")"
  api GET "/groups?search=${encoded}&exact=true" | jq -er --arg name "${name}" '.[] | select(.name == $name) | .id' | head -n 1
}

find_user_id() {
  local username="$1" encoded
  encoded="$(urlencode "${username}")"
  api GET "/users?username=${encoded}&exact=true" | jq -er --arg username "${username}" '.[] | select(.username == $username) | .id' | head -n 1
}

random_password() {
  python3 - <<'PY'
import secrets
alphabet = 'ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz23456789!@#%+=_-'
print(''.join(secrets.choice(alphabet) for _ in range(24)))
PY
}


if [[ "${delete_all_participants}" == true ]]; then
  deleted_users=0
  deleted_groups=0

  # Validate every target group before deleting anything. A group with another
  # member may be shared and must not be removed by this workshop helper.
  for index in "${!workers[@]}"; do
    username="$(printf '%s%02d' "${group_prefix}" "$((index + 1))")"

    if group_id="$(find_group_id "${username}" 2>/dev/null)"; then
      unexpected_members="$(
        api GET "/groups/${group_id}/members?first=0&max=1000" |
          jq -r --arg username "${username}" \
            '[.[] | select(.username != $username) | .username] | join(", ")'
      )"
      [[ -z "${unexpected_members}" ]] || \
        fail "Refusing to delete group '${username}': non-participant member(s): ${unexpected_members}"
    fi
  done

  for index in "${!workers[@]}"; do
    username="$(printf '%s%02d' "${group_prefix}" "$((index + 1))")"

    if user_id="$(find_user_id "${username}" 2>/dev/null)"; then
      api DELETE "/users/${user_id}" >/dev/null
      info "Deleted participant: ${username}"
      deleted_users=$((deleted_users + 1))
    else
      info "Participant already absent: ${username}"
    fi

    if group_id="$(find_group_id "${username}" 2>/dev/null)"; then
      api DELETE "/groups/${group_id}" >/dev/null
      info "Deleted Keycloak group: ${username}"
      deleted_groups=$((deleted_groups + 1))
    else
      info "Keycloak group already absent: ${username}"
    fi
  done

  printf 'Participant deletion complete: users_deleted=%d, groups_deleted=%d, selected=%d.\n' \
    "${deleted_users}" "${deleted_groups}" "${selected_count}"
  exit 0
fi

created=0
reset=0
existing=0
for index in "${!workers[@]}"; do
  number=$((index + 1))
  username="$(printf '%s%02d' "${group_prefix}" "${number}")"

  [[ "${reset_all_passwords}" == true || -z "${reset_password_for}" || "${username}" == "${reset_password_for}" ]] || continue

  if [[ "${reset_all_passwords}" == true || -n "${reset_password_for}" ]]; then
    if group_id="$(find_group_id "${username}" 2>/dev/null)"; then
      :
    elif [[ "${create_missing}" == true ]]; then
      api POST '/groups' --data "$(jq -cn --arg name "${username}" '{name: $name}')" >/dev/null
      group_id="$(find_group_id "${username}")" || fail "Created group '${username}' but could not retrieve it"
      info "Created Keycloak group: ${username}"
    else
      fail "Cannot reset '${username}': the matching Keycloak group was not found"
    fi

    if user_id="$(find_user_id "${username}" 2>/dev/null)"; then
      :
    elif [[ "${create_missing}" == true ]]; then
      api POST '/users' --data "$(jq -cn --arg username "${username}" '{username: $username, enabled: true, emailVerified: false}')" >/dev/null
      user_id="$(find_user_id "${username}")" || fail "Created user '${username}' but could not retrieve it"
      info "Created participant: ${username}"
      created=$((created + 1))
    else
      fail "Cannot reset '${username}': the existing Keycloak user was not found"
    fi

    password="$(random_password)"
    api PUT "/users/${user_id}/reset-password" \
      --data "$(jq -cn --arg value "${password}" '{type: "password", value: $value, temporary: true}')" >/dev/null
    printf '%s\t%s\t%s\n' "${username}" "${password}" "${workers[index]}" >> "${credentials_tmp}"
    credential_records=$((credential_records + 1))
    info "Reset participant password: ${username} (temporary password; change required at next login)"
    unset password
    api POST "/users/${user_id}/logout" >/dev/null
    api PUT "/users/${user_id}/groups/${group_id}" >/dev/null
    reset=$((reset + 1))
    continue
  fi

  if group_id="$(find_group_id "${username}" 2>/dev/null)"; then
    :
  else
    api POST '/groups' --data "$(jq -cn --arg name "${username}" '{name: $name}')" >/dev/null
    group_id="$(find_group_id "${username}")" || fail "Created group '${username}' but could not retrieve it"
    info "Created Keycloak group: ${username}"
  fi

  if user_id="$(find_user_id "${username}" 2>/dev/null)"; then
    api PUT "/users/${user_id}/groups/${group_id}" >/dev/null
    info "Reconciled existing participant: ${username}"
    existing=$((existing + 1))
    continue
  fi

  api POST '/users' --data "$(jq -cn --arg username "${username}" '{username: $username, enabled: true, emailVerified: false}')" >/dev/null
  user_id="$(find_user_id "${username}")" || fail "Created user '${username}' but could not retrieve it"
  password="$(random_password)"
  api PUT "/users/${user_id}/reset-password" --data "$(jq -cn --arg value "${password}" '{type: "password", value: $value, temporary: true}')" >/dev/null
  api PUT "/users/${user_id}/groups/${group_id}" >/dev/null

  printf '%s\t%s\t%s\n' "${username}" "${password}" "${workers[index]}" >> "${credentials_tmp}"
    credential_records=$((credential_records + 1))
  info "Created participant: ${username}"
  unset password
  created=$((created + 1))
done

if [[ -e "${credentials_output}" ]]; then
  fail "Credentials output appeared during processing; refusing to overwrite it: ${credentials_output}"
fi
mv -- "${credentials_tmp}" "${credentials_output}"
credentials_tmp=""
trap - EXIT

printf 'Participant account preparation complete: created=%d, reset=%d, existing=%d, selected=%d.\n' \
  "${created}" "${reset}" "${existing}" "${selected_count}"
printf 'New credentials (mode 0600): %s\n' "${credentials_output}"
